package eu.agricore.ardit.interfac;

import org.apache.tomcat.util.http.LegacyCookieProcessor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import org.springframework.boot.web.server.WebServerFactoryCustomizer;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class InterfaceApplication {


    public static void main(String[] args) {

        SpringApplication.run(InterfaceApplication.class, args);

    }
	
	/*@Bean
	CommandLineRunner runner() {
		return args -> {
			List<LdapUser> users = userManagementService.findAll();
			
			for(LdapUser user: users) {
				AppUser newAppUser = new AppUser(user.getUsername(), user.getEmail(), null, true, false, false, null);
				appUserService.saveAppUser(newAppUser);
			}
		};
	}*/


    /**
     * This method parses JSON files which contain vocabularies values associated with some dataset's attributes
     *
     */
	/*@Bean
	CommandLineRunner runner(VocabularyLoader vocabularyLoader) {
		return args -> {
			vocabularyLoader.loadVocabularies();
		};
	}*/

    /**
     * This method corrects an error generated by Tomcat when a cookie is set with spaces in the value
     * In our case, we have one space between the Bearer statement and the token chain
     */
    @Bean
    public WebServerFactoryCustomizer<TomcatServletWebServerFactory> cookieProcessorCustomizer() {
        return (serverFactory) -> serverFactory.addContextCustomizers(
                (context) -> context.setCookieProcessor(new LegacyCookieProcessor()));
    }
}
